# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name_bangla', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_bangla', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('union_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_bangla', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.District')),
            ],
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('upazila_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name_bangla', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.District')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_bangla', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('union', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Union')),
                ('upazila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Upazila')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_bangla', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('union_word_no', models.CharField(max_length=6)),
                ('union', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Union')),
                ('upazila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Upazila')),
            ],
        ),
        migrations.AddField(
            model_name='village',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Word'),
        ),
        migrations.AddField(
            model_name='union',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Upazila'),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division', to='country.Division'),
        ),
    ]
