# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20170430_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='village_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_code',
            field=models.CharField(max_length=10),
        ),
    ]
