# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.CharField(db_index=True, max_length=25, primary_key=True, serialize=False)),
                ('name_bangla', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('nid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('B', 'Both')], max_length=10, null=True)),
                ('post_office', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('spouse_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Union')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Village')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Word')),
            ],
        ),
    ]
